### ISSUE TITLE
bug: `FitOptimizer.__init__()` got an unexpected keyword argument 'freeze_fun'

### ISSUE THREAD

**Issue by PaulScemama** [awslabs/fortuna#59]
# Bug Report

**Fortuna version:** 0.1.14

**Current behavior:** From [this example](https://github.com/awslabs/fortuna/blob/main/examples/mnist_classification.pct.py), when I run 
```python
output_dim = 10
prob_model = ProbClassifier(
    model=LeNet5(output_dim=output_dim),
    posterior_approximator=LaplacePosteriorApproximator(),
)

status = prob_model.train(
    train_data_loader=train_data_loader,
    val_data_loader=val_data_loader,
    calib_data_loader=val_data_loader,
    fit_config=FitConfig(
        optimizer=FitOptimizer(freeze_fun=lambda path, val: "trainable" if "output_subnet" in path else "frozen")
    ),
    map_fit_config=FitConfig(
        monitor=FitMonitor(early_stopping_patience=2, metrics=(accuracy,)),
        optimizer=FitOptimizer()
    ),
    calib_config=CalibConfig(monitor=CalibMonitor(early_stopping_patience=2))
)
```

I get 

```bash
TypeError: FitOptimizer.__init__() got an unexpected keyword argument 'freeze_fun'
```

**Expected behavior:** For the example to run without error. 

**Steps to reproduce:** I created a virtual environment with poetry. I ran `poetry add aws-fortuna` to install fortuna. 

**Related code:**

**Other information:**

**Comment by gianlucadetommaso** [comment]
Hi Paul, thanks for raising this! It works when cloning from GitHub, but the PyPi release was behind. I now released `0.1.15` on PyPi. Just run `pip install --upgrade aws-fortuna` and it should work. 😄
