### ISSUE TITLE
Example with Time Series Data ?

### ISSUE THREAD

**Issue by msh855** [awslabs/fortuna#6]
Is the library suitable for time series data?

**Comment by gianlucadetommaso** [comment]
Hi Mustafa,
thanks for raising this issue! Currently we do not explicitly support a temporal framework. Nevertheless, if you can split time series data into training, validation and test sets, there is nothing blocking you from using Fortuna's algorithms to quantify the uncertainty of your model predictions.

Perhaps you could give me more info about the type of application that you have in mind? You are not the first customer asking about time series and forecasting. If several users ask for the same use case, we may consider trying to support it explicitly, or provide some examples.

**Comment by msh855** [comment]
I was just experimenting with the library for time-series forecasting. 

The Validation and test sets need to keep the temporal structure (that's user's design). But I cannot understand how the package will work or is working in such exercise.

**Comment by gianlucadetommaso** [comment]
Methods for this, in particular in the space of conformal prediction, may be added soon. Currently they are not yet supported.

**Comment by msh855** [comment]
Looking forward to it. Please update the community, I think there is a lot of interest on this area.

**Comment by gianlucadetommaso** [comment]
Hi Moustafa,
we are starting to support uncertainty quantification methods for time series data. For now we included [EnbPI](http://proceedings.mlr.press/v139/xu21h/xu21h.pdf), a conformal prediction method for time series regression.

Please find an example here: https://aws-fortuna.readthedocs.io/en/latest/examples/enbpi_ts_regression.html

**Comment by msh855** [comment]
Great, work. I will have a look. Thanks
