### ISSUE TITLE
Documentation: Inconsistent outputs

### ISSUE THREAD

**Issue by thomaspinder** [awslabs/fortuna#9]
Some docs have rendered output e.g., [Sinusoidal regression](https://aws-fortuna.readthedocs.io/en/latest/examples/sinusoidal_regression.html), whereas others, such as [MNIST Classification](https://aws-fortuna.readthedocs.io/en/latest/examples/mnist_classification.html) do not. 

We should render the notebooks in a CI/CD loop. This would yield two benefits: 1) fully rendered and up-to-date notebooks, and 2) bug catching - if there's a change to the codebase that breaks a notebook, this workflow will catch it. 

As a further consideration, letting the notebooks be `.py` files and converting them to notebooks with Jupytext would make the version control simpler.

If approved, I'd be happy to open a PR for this.

**Comment by gianlucadetommaso** [comment]
Yes good points, thanks. I agree that it's best to have all notebooks rendered. Feel free to go forward with this!

Thanks a lot.

**Comment by gianlucadetommaso** [comment]
About the conversion from `.py` to notebook, I've never done this but happy to check what your solution would be.

**Comment by thomaspinder** [comment]
Great. I'll split this issue into two.
