### ISSUE TITLE
Bug: Init doesn't work when the input data is a dictionary

### ISSUE THREAD

**Issue by dpsimpson** [awslabs/fortuna#92]
Hi, I've run into an annoying bug when trying to run the model.

Basically the following line of code assumes that input_shape is a tuple, but `get_input_shape`, which is used in `ProbClassifier._check_output_dim` to get the `input_shape` is the result of a tree map. So when the input is `Dict[str, Array]`, `input_shape` has type `Dict[str, Tuple]. 

The problem his that `Joint.init`, linked below, doesn't cover this case.
https://github.com/awslabs/fortuna/blob/c277435710b7f9552ea0c46af3c4c5cdf38d3ffb/fortuna/model/model_manager/classification.py#L107

This seems to be an assumption throughout the library. Maybe there should be a high level error when making a data loader if input is a dictionary.

**Comment by gianlucadetommaso** [comment]
Hi Dan,
thanks for raising this! Do you want to submit a PR yourself? Otherwise I can go on and fix this.

Could you also share what model are you trying to use? In the past I haven't encountered this problem.

**Comment by dpsimpson** [comment]
I’m playing around with RoBERTa, which needs two inputs (input_ids and
attention_mask). I tried to spot patch the function I flagged but the
assumption that it’s a tuple seems to be deeper

**Comment by gianlucadetommaso** [comment]
RoBERTa should work though - I've been running experiments with it just yesterday. 

Perhaps you can try and run [this](example) here and set `--model_name_or_path roberta-base`?

**Comment by dpsimpson** [comment]
Weird! (That link is dead)

**Comment by gianlucadetommaso** [comment]
My bad, can you try clicking it again?

**Comment by dpsimpson** [comment]
ok that runs. Phew. That means the error is somewhere in my data handling. Thanks

**Comment by gianlucadetommaso** [comment]
Great, let me know if I can help!
