### ISSUE TITLE
bug: `model.__call__()` got an unexpected keyword argument 'train' when training custom model class.

### ISSUE THREAD

**Issue by PaulScemama** [awslabs/fortuna#98]
# Bug Report

**Fortuna version:** 0.1.17

**Current behavior:**

When bringing own model class, and then trying to run `prob_model.train()`, it leads to the following error:
```bash
TypeError: model_class.__call__() got an unexpected keyword argument 'train'
```

**Expected behavior:** That the model trains.

**Related code:**

```python
import flax.linen as nn
from fortuna.prob_model import ProbClassifier
from fortuna.data import DataLoader 
from fortuna.prob_model import FitConfig

class CNN(nn.Module):
    @nn.compact
    def __call__(self, x):
        x = nn.Conv(features=32, kernel_size=(3, 3))(x)
        x = nn.relu(x)
        x = nn.avg_pool(x, window_shape=(2, 2), strides=(2, 2))
        x = nn.Conv(features=64, kernel_size=(3, 3))(x)
        x = nn.relu(x)
        x = nn.avg_pool(x, window_shape=(2, 2), strides=(2, 2))
        x = x.reshape((x.shape[0], -1))  # flatten
        x = nn.Dense(features=256)(x)
        x = nn.relu(x)
        x = nn.Dense(features=10)(x)
        x = nn.log_softmax(x)
        return x
    
prob_model = ProbClassifier(model=CNN())


x = jnp.zeros((5, 64, 64, 10))
y = jnp.ones((5,))

train_loader = DataLoader.from_array_data(
    data=(x,y), batch_size=1
)

prob_model.train(
    train_loader,
    fit_config=FitConfig(
    )
)
# RAISES ERROR
```

**Comment by gianlucadetommaso** [comment]
Hi Paul,
thanks for raising this, I need to clarify this in the documentation. The signature of your `__call__` function expects a `train` variable. This is useful for models with dropout, for example.

You can solve the issue by simply changing `def __call__(self, x):` into `def __call__(self, x, **kwargs):`.

Notice that the model also checks whether the number of classes in the data corresponds to the number of logits. If you want to run this just as an example, you my want to redefine `y` to something like `y = jnp.arange(10)[None].repeat(5, axis=0)`.

**Comment by PaulScemama** [comment]
@gianlucadetommaso thanks! Sounds good, it works now with your suggestion of adding `**kwargs` in the `__call__` arguments.
